// setup-admin.js — Run once: node setup-admin.js
// Fixes: JWT_SECRET missing, admins table missing, wrong password hash
const fs     = require('fs');
const path   = require('path');

// ── Step 0: Ensure .env exists with JWT_SECRET ────────────────
const envPath = path.join(__dirname, '.env');
if (!fs.existsSync(envPath)) {
  console.log('⚠️   .env file not found — creating one...');
  fs.writeFileSync(envPath, [
    '# Critix Backend — auto-generated by setup-admin.js',
    'PORT=5000',
    'NODE_ENV=development',
    'DB_HOST=localhost',
    'DB_PORT=3306',
    'DB_USER=root',
    'DB_PASSWORD=',
    'DB_NAME=critix',
    'JWT_SECRET=critix-super-secret-jwt-key-2024',
    'JWT_EXPIRES_IN=7d',
    'CLIENT_URL=http://localhost:5173',
  ].join('\n') + '\n');
  console.log('✅  .env created');
} else {
  // Check if JWT_SECRET line exists and is not commented out
  let envContent = fs.readFileSync(envPath, 'utf8');
  if (!/^JWT_SECRET\s*=\s*.+/m.test(envContent)) {
    console.log('⚠️   JWT_SECRET missing or commented out in .env — adding it...');
    envContent += '\nJWT_SECRET=critix-super-secret-jwt-key-2024\n';
    fs.writeFileSync(envPath, envContent);
    console.log('✅  JWT_SECRET added to .env');
  }
}

require('dotenv').config();
const mysql  = require('mysql2/promise');
const bcrypt = require('bcryptjs');

const ADMIN = {
  first_name:    'Tajin Ahmed',
  last_name:     'Mahin',
  email:         'tajinahmed007@gmail.com',
  plainPassword: 'Tajin007!',
};

(async () => {
  console.log('\n🔧  Critix Admin Setup\n');
  console.log('✅  JWT_SECRET:', process.env.JWT_SECRET ? 'found' : 'using fallback');

  let conn;
  try {
    conn = await mysql.createConnection({
      host:     process.env.DB_HOST     || 'localhost',
      port:     process.env.DB_PORT     || 3306,
      user:     process.env.DB_USER     || 'root',
      password: process.env.DB_PASSWORD || '',
      database: process.env.DB_NAME     || 'critix',
    });
    console.log('✅  MySQL connected');
  } catch (err) {
    console.error('❌  Cannot connect to MySQL:', err.message);
    console.error('\n    Make sure XAMPP/MySQL is running and .env has correct DB settings\n');
    process.exit(1);
  }

  // Ensure admins table
  await conn.execute(`
    CREATE TABLE IF NOT EXISTS admins (
      id            INT AUTO_INCREMENT PRIMARY KEY,
      first_name    VARCHAR(80)  NOT NULL,
      last_name     VARCHAR(80)  NOT NULL,
      email         VARCHAR(120) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
  `);
  console.log('✅  admins table ready');

  // Check existing
  const [existing] = await conn.execute('SELECT * FROM admins WHERE email = ?', [ADMIN.email]);

  if (existing.length > 0) {
    // Verify and fix hash if needed
    const valid = await bcrypt.compare(ADMIN.plainPassword, existing[0].password_hash);
    if (!valid) {
      console.log('⚠️   Password hash mismatch — resetting...');
      const newHash = await bcrypt.hash(ADMIN.plainPassword, 10);
      await conn.execute('UPDATE admins SET password_hash = ? WHERE email = ?', [newHash, ADMIN.email]);
      console.log('✅  Password hash reset');
    } else {
      console.log('✅  Admin account exists and password is correct');
    }
  } else {
    const hash = await bcrypt.hash(ADMIN.plainPassword, 10);
    await conn.execute(
      'INSERT INTO admins (first_name, last_name, email, password_hash) VALUES (?,?,?,?)',
      [ADMIN.first_name, ADMIN.last_name, ADMIN.email, hash]
    );
    console.log('✅  Admin account created');
  }

  await conn.end();
  console.log('\n🎉  All done! Login at http://localhost:5173/login → Admin tab');
  console.log(`    Email:    ${ADMIN.email}`);
  console.log(`    Password: ${ADMIN.plainPassword}\n`);
})();
