-- ═══════════════════════════════════════════════════════════
-- Critix Database — Run this ONCE in phpMyAdmin → SQL tab
-- ═══════════════════════════════════════════════════════════

CREATE DATABASE IF NOT EXISTS critix CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE critix;

-- ─── TABLES ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url VARCHAR(500) DEFAULT NULL,
    bio TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type ENUM('movie', 'tv') NOT NULL DEFAULT 'movie',
    title VARCHAR(255) NOT NULL,
    year SMALLINT NOT NULL,
    rating DECIMAL(3, 1) DEFAULT 0.0,
    critics TINYINT DEFAULT 0,
    genre JSON NOT NULL,
    poster VARCHAR(500) DEFAULT NULL,
    backdrop VARCHAR(500) DEFAULT NULL,
    director VARCHAR(120) DEFAULT NULL,
    tagline VARCHAR(255) DEFAULT NULL,
    synopsis TEXT DEFAULT NULL,
    runtime VARCHAR(30) DEFAULT NULL,
    popular SMALLINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    movie_id INT NOT NULL,
    user_id INT NOT NULL,
    rating TINYINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    text TEXT NOT NULL,
    mood VARCHAR(50) DEFAULT NULL,
    quote VARCHAR(500) DEFAULT NULL,
    is_spoiler BOOLEAN DEFAULT FALSE,
    visibility ENUM('public') DEFAULT 'public',
    rewatch TINYINT DEFAULT 5,
    likes_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_likes (
    user_id INT NOT NULL,
    review_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, review_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS watchlist (
    user_id INT NOT NULL,
    movie_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, movie_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (movie_id) REFERENCES movies (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS discussions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    tags JSON DEFAULT NULL,
    likes_count INT DEFAULT 0,
    views INT DEFAULT 0,
    replies INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- ─── SEED: USERS ─────────────────────────────────────────────
-- All passwords = "password123"
-- FIX: Replaced the wrong Laravel "password" hash with the correct bcrypt hash for "password123"
INSERT IGNORE INTO
    users (
        id,
        username,
        email,
        password_hash,
        avatar_url
    )
VALUES (
        1,
        'jobayer_mahin',
        'jobayer123@gmail.com',
        '$2a$10$UIzv8tErUQfKx8FfMVsDHuM2tybMhTbTgCfDnAqEkUE3ZKb8PoH4S',
        '/jobayer-avatar.jpg'
    ),
    (
        2,
        'arzuWu',
        'arzu123@gmail.com',
        '$2a$10$UIzv8tErUQfKx8FfMVsDHuM2tybMhTbTgCfDnAqEkUE3ZKb8PoH4S',
        '/arzu-avatar.jpg'
    ),
    (
        3,
        'astroboy',
        'tazinahmed123@gmail.com',
        '$2a$10$UIzv8tErUQfKx8FfMVsDHuM2tybMhTbTgCfDnAqEkUE3ZKb8PoH4S',
        '/astroboy-avatar.jpg'
    ),
    (
        4,
        'gracie3',
        'gracie123@gmail.com',
        '$2a$10$UIzv8tErUQfKx8FfMVsDHuM2tybMhTbTgCfDnAqEkUE3ZKb8PoH4S',
        '/gracie-avatar.jpg'
    ),
    (
        5,
        'spaeny0',
        'spaeny123@gmail.com',
        '$2a$10$UIzv8tErUQfKx8FfMVsDHuM2tybMhTbTgCfDnAqEkUE3ZKb8PoH4S',
        'spaeny-avatar.jpg'
    );

-- ─── SEED: MOVIES ────────────────────────────────────────────
INSERT IGNORE INTO
    movies (
        id,
        type,
        title,
        year,
        rating,
        critics,
        genre,
        poster,
        backdrop,
        director,
        tagline,
        popular,
        runtime,
        synopsis
    )
VALUES (
        1,
        'movie',
        'Dune: Part Two',
        2024,
        8.9,
        94,
        '["Sci-Fi","Adventure","Drama"]',
        '/dune-part-two-poster.jpg',
        '/dune-part-two-backdrop.jpg',
        'Denis Villeneuve',
        'Long live the fighters.',
        99,
        '2h 46m',
        'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.'
    ),
    (
        2,
        'movie',
        'Oppenheimer',
        2023,
        9.0,
        93,
        '["Biography","Drama","History"]',
        '/oppenheimer-poster.jpg',
        '/oppenheimer-backdrop.jpg',
        'Christopher Nolan',
        'The world forever changes.',
        98,
        '3h 0m',
        'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.'
    ),
    (
        3,
        'tv',
        'Shogun',
        2024,
        8.9,
        99,
        '["Drama","History","Action"]',
        '/shogun-poster.jpg',
        '/shogun-backdrop.jpg',
        'Rachel Kondo',
        'Power is the ultimate prize.',
        97,
        '10 Episodes',
        'A mysterious English navigator arrives in feudal Japan and becomes entangled in a clash of power between a powerful lord and his enemies.'
    ),
    (
        4,
        'tv',
        'The Bear',
        2024,
        8.7,
        98,
        '["Drama","Comedy"]',
        '/the-bear-poster.jpg',
        '/the-bear-backdrop.jpg',
        'Christopher Storer',
        'Every second counts.',
        95,
        '10 Episodes',
        'The crew of The Bear restaurant navigates the pressures of running a fine dining establishment while dealing with personal demons.'
    ),
    (
        5,
        'movie',
        'Poor Things',
        2023,
        8.2,
        92,
        '["Fantasy","Comedy","Drama"]',
        '/poor-things-poster.jpg',
        '/poor-things-backdrop.jpg',
        'Yorgos Lanthimos',
        'An incredible adventure of self-discovery.',
        88,
        '2h 21m',
        'The incredible tale of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.'
    ),
    (
        6,
        'movie',
        'Past Lives',
        2023,
        8.3,
        94,
        '["Romance","Drama"]',
        '/past-lives-poster.jpg',
        '/past-lives-backdrop.jpg',
        'Celine Song',
        'You can''t lose what you never had.',
        84,
        '1h 46m',
        'Nora and Hae Sung, two deeply connected childhood friends, are separated when Nora''s family emigrates from South Korea. Decades later, they reunite in New York.'
    ),
    (
        7,
        'tv',
        'Succession',
        2023,
        9.1,
        97,
        '["Drama","Comedy"]',
        '/succession-poster.jpg',
        '/succession-backdrop.jpg',
        'Jesse Armstrong',
        'Who''s next?',
        96,
        '10 Episodes',
        'The Roy family navigates the uncertain future of Waystar RoyCo, a global media and entertainment conglomerate.'
    ),
    (
        8,
        'movie',
        'Killers of the Flower Moon',
        2023,
        8.1,
        93,
        '["Crime","Drama","History"]',
        '/killers-of-the-flower-moon-poster.jpg',
        '/killers-of-the-flower-moon-backdrop.jpg',
        'Martin Scorsese',
        'Based on a true crime.',
        89,
        '3h 26m',
        'Members of the Osage Nation are murdered under mysterious circumstances in the 1920s, sparking a major FBI investigation.'
    ),
    (
        9,
        'movie',
        'Spider-Man: Across the Spider-Verse',
        2023,
        8.9,
        95,
        '["Animation","Action","Adventure"]',
        '/spiderman-accross-the-spider-verse-poster.jpg',
        '/spiderman-accross-the-spider-verse-backdrop.jpg',
        'Joaquim Dos Santos',
        'It''s how you wear the mask.',
        97,
        '2h 20m',
        'Miles Morales catapults across the multiverse, where he encounters a team of Spider-People charged with protecting its very existence.'
    ),
    (
        10,
        'movie',
        'The Holdovers',
        2023,
        8.1,
        96,
        '["Comedy","Drama"]',
        '/the-holdovers-poster.jpg',
        '/the-holdovers-backdrop.jpg',
        'Alexander Payne',
        'Bonds forged in detention.',
        82,
        '2h 13m',
        'A curmudgeonly instructor at a New England prep school is forced to remain on campus during the holidays with a troublesome student.'
    ),
    (
        11,
        'movie',
        'Anatomy of a Fall',
        2023,
        8.0,
        96,
        '["Thriller","Drama","Mystery"]',
        '/anatomy-of-a-fall-poster.jpg',
        '/anatomy-of-a-fall-backdrop.jpg',
        'Justine Triet',
        'Who is responsible?',
        80,
        '2h 31m',
        'A woman is suspected of murdering her husband when he''s found dead near their secluded home. Their visually impaired son faces a conflict between love and truth.'
    ),
    (
        12,
        'tv',
        'The Last of Us',
        2023,
        8.8,
        96,
        '["Drama","Action","Sci-Fi"]',
        '/the-last-of-us-poster.jpg',
        '/the-last-of-us-backdrop.jpg',
        'Craig Mazin',
        'We survive together.',
        96,
        '9 Episodes',
        'Joel, a hardened survivor, is hired to smuggle Ellie out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey.'
    ),
    (
        13,
        'movie',
        'Saltburn',
        2023,
        7.3,
        71,
        '["Thriller","Drama"]',
        '/saltburn-poster.jpg',
        '/saltburn-backdrop.jpg',
        'Emerald Fennell',
        'Welcome to his world.',
        86,
        '2h 11m',
        'Struggling student Oliver Quick finds himself drawn into the world of the charming and charismatic Felix Catton, who invites him to his estate for the summer.'
    ),
    (
        14,
        'movie',
        'Barbie',
        2023,
        7.8,
        88,
        '["Comedy","Fantasy"]',
        '/barbie-poster.jpg',
        '/barbie-backdrop.jpg',
        'Greta Gerwig',
        'She was never meant for reality.',
        93,
        '1h 54m',
        'Barbie and Ken are having the time of their lives in Barbie Land. When they find themselves in the real world, they discover the joys and perils of living among humans.'
    ),
    (
        15,
        'tv',
        'Beef',
        2023,
        8.7,
        98,
        '["Comedy","Drama","Thriller"]',
        '/beef-poster.jpg',
        '/beef-backdrop.jpg',
        'Lee Sung Jin',
        'A feud that changes everything.',
        90,
        '10 Episodes',
        'A road rage incident between two strangers spirals into an ongoing feud that brings out their worst impulses and exposes their deepest vulnerabilities.'
    ),
    (
        16,
        'movie',
        'American Fiction',
        2023,
        7.8,
        92,
        '["Comedy","Drama"]',
        '/american-fiction-poster.jpg',
        '/american-fiction-backdrop.jpg',
        'Cord Jefferson',
        'The truth about fiction.',
        79,
        '1h 57m',
        'A frustrated novelist uses a pen name to write a book he believes is the most outlandish stereotype of Black literature he can think of.'
    ),
    (
        17,
        'tv',
        'The White Lotus',
        2023,
        8.6,
        95,
        '["Drama","Comedy","Mystery"]',
        '/the-white-lotus-poster.jpg',
        '/the-white-lotus-backdrop.jpg',
        'Mike White',
        'Paradise has a price.',
        85,
        '7 Episodes',
        'An assortment of guests arrive at a Sicilian resort over a week and slowly reveal their peculiarities and dark secrets.'
    ),
    (
        18,
        'tv',
        'Severance',
        2023,
        8.4,
        97,
        '["Drama","Thriller","Mystery"]',
        '/severance-poster.jpg',
        '/severance-backdrop.jpg',
        'Dan Erickson',
        'Work and life. Perfectly balanced.',
        82,
        '9 Episodes',
        'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.'
    ),
    (
        19,
        'movie',
        'The Shawshank Redemption',
        1994,
        9.3,
        99,
        '["Drama"]',
        '/shawshank-redemption-poster.jpg',
        '/shawshank-redemption-backdrop.jpg',
        'Frank Darabont',
        'Fear can hold you prisoner. Hope can set you free.',
        99,
        '2h 22m',
        'Andy Dufresne is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the years, he forms a friendship with fellow inmate Red and maintains hope.'
    ),
    (
        20,
        'movie',
        'Se7en',
        1995,
        8.6,
        91,
        '["Crime","Drama","Mystery"]',
        '/se7en-poster.jpg',
        '/se7en-backdrop.jpg',
        'David Fincher',
        'Seven deadly sins. Seven ways to die.',
        90,
        '2h 7m',
        'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.'
    ),
    (
        21,
        'movie',
        'La La Land',
        2016,
        8.0,
        91,
        '["Comedy","Drama","Music","Romance"]',
        '/la-la-land-poster.jpg',
        '/la-la-land-backdrop.jpg',
        'Damien Chazelle',
        'Here''s to the ones who dream.',
        92,
        '2h 8m',
        'A jazz pianist and an aspiring actress fall in love while pursuing their dreams in Los Angeles, but their ambitions threaten to pull them apart.'
    ),
    (
        22,
        'movie',
        'Blade Runner 2049',
        2017,
        8.0,
        88,
        '["Sci-Fi","Drama","Mystery"]',
        '/blade-runner-2049-poster.jpg',
        '/blade-runner-2049-backdrop.jpg',
        'Denis Villeneuve',
        'The key to the future is finally unearthed.',
        87,
        '2h 44m',
        'Officer K, a new blade runner for the LAPD, unearths a long-buried secret that leads him to track down former blade runner Rick Deckard, who has been missing for thirty years.'
    ),
    (
        23,
        'movie',
        'Spider-Man: Into the Spider-Verse',
        2018,
        8.4,
        97,
        '["Animation","Action","Adventure"]',
        '/spiderman-into-the-spider-verse-poster.jpg',
        '/spiderman-into-the-spider-verse-backdrop.jpg',
        'Bob Persichetti',
        'More than one wears the mask.',
        96,
        '1h 57m',
        'Teen Miles Morales becomes the Spider-Man of his universe and crosses paths with five counterparts from other dimensions to stop a threat for all realities.'
    ),
    (
        24,
        'movie',
        'Ford v Ferrari',
        2019,
        8.1,
        92,
        '["Action","Biography","Drama"]',
        '/ford-v-ferrari-poster.jpg',
        '/ford-v-ferrari-backdrop.jpg',
        'James Mangold',
        'The race against time begins.',
        85,
        '2h 32m',
        'American car designer Carroll Shelby and driver Ken Miles work together to build a revolutionary race car for Ford and challenge Ferrari at the 24 Hours of Le Mans in 1966.'
    ),
    (
        25,
        'movie',
        'Parasite',
        2019,
        8.5,
        99,
        '["Comedy","Drama","Thriller"]',
        '/parasite-poster.jpg',
        '/parasite-backdrop.jpg',
        'Bong Joon Ho',
        'Act like you own the place.',
        96,
        '2h 12m',
        'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim family.'
    ),
    (
        26,
        'movie',
        'Another Round',
        2020,
        7.7,
        94,
        '["Comedy","Drama"]',
        '/another-round-poster.jpg',
        '/another-round-backdrop.jpg',
        'Thomas Vinterberg',
        'It''s never too late for a wake-up call.',
        78,
        '1h 57m',
        'Four high school teachers test a theory that a constant low level of alcohol in the blood opens us up to the world, hoping to find new joy and energy in their work and personal lives.'
    ),
    (
        27,
        'movie',
        'Top Gun: Maverick',
        2022,
        8.2,
        96,
        '["Action","Drama"]',
        '/top-gun-maverick-poster.jpg',
        '/top-gun-maverick-backdrop.jpg',
        'Joseph Kosinski',
        'Feel the need for speed.',
        95,
        '2h 10m',
        'After thirty years, Maverick is still pushing the envelope as a top naval aviator, training a new generation of pilots for a dangerous mission that demands the ultimate sacrifice.'
    ),
    (
        28,
        'movie',
        'Everything Everywhere All at Once',
        2022,
        7.8,
        95,
        '["Action","Adventure","Comedy","Sci-Fi"]',
        '/everything-everywhere-all-at-once-poster.jpg',
        '/everything-everywhere-all-at-once-backdrop.jpg',
        'Daniel Kwan',
        'The universe is so much bigger than you realize.',
        91,
        '2h 19m',
        'A burnt-out laundromat owner is swept into an insane adventure where she alone can save existence by exploring other universes connecting with the lives she could have led.'
    ),
    (
        29,
        'movie',
        'The Wild Robot',
        2024,
        8.2,
        97,
        '["Animation","Adventure","Family","Sci-Fi"]',
        '/the-wild-robot-poster.jpg',
        '/the-wild-robot-backdrop.jpg',
        'Chris Sanders',
        'Adapt to survive.',
        92,
        '1h 42m',
        'After a shipwreck, a robot named Roz is stranded on an uninhabited island. To survive in the harsh environment, she activates her programming and learns from the animals on the island, eventually becoming the adoptive parent of an orphaned gosling.'
    ),
    (
        30,
        'movie',
        'Sinners',
        2025,
        8.1,
        95,
        '["Horror","Thriller","Drama"]',
        '/sinners-poster.jpg',
        '/sinners-backdrop.jpg',
        'Ryan Coogler',
        'Come on down, they''re waiting for you.',
        90,
        '2h 17m',
        'Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.'
    ),
    (
        31,
        'movie',
        'F1: The Movie',
        2025,
        7.8,
        84,
        '["Action","Drama","Sport"]',
        '/f1-the-movie-poster.jpg',
        '/f1-the-movie-backdrop.jpg',
        'Joseph Kosinski',
        'Speed is the price of greatness.',
        88,
        '2h 36m',
        'A Formula 1 driver who left the sport in the 1990s returns decades later as a mentor and driver for a struggling team, partnering with a young rookie eager to prove himself.'
    ),
    (
        32,
        'movie',
        'The Green Mile',
        1999,
        8.6,
        80,
        '["Crime","Drama","Fantasy"]',
        '/the-green-mile-poster.jpg',
        '/the-green-mile-backdrop.jpg',
        'Frank Darabont',
        'Walk a mile you''ll never forget.',
        91,
        '3h 9m',
        'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.'
    ),
    (
        33,
        'movie',
        'About Time',
        2013,
        7.8,
        68,
        '["Comedy","Drama","Fantasy","Romance"]',
        '/about-time-poster.jpg',
        '/about-time-backdrop.jpg',
        'Richard Curtis',
        'The story of a remarkable family.',
        80,
        '2h 3m',
        'At the age of 21, Tim discovers he can travel in time and decides the thing he really wants to do is find a girlfriend. But time travel turns out not to be as simple as he thought.'
    ),
    (
        34,
        'movie',
        'Manchester by the Sea',
        2016,
        7.8,
        96,
        '["Drama"]',
        '/manchester-by-the-sea-poster.jpg',
        '/manchester-by-the-sea-backdrop.jpg',
        'Kenneth Lonergan',
        'From the deepest wounds, sometimes the best parts of us emerge.',
        84,
        '2h 17m',
        'A depressed man is forced to deal with his past when his older brother dies, leaving him as guardian to his teenage nephew.'
    ),
    (
        35,
        'movie',
        'The Pursuit of Happyness',
        2006,
        8.0,
        64,
        '["Biography","Drama"]',
        '/the-pursuit-of-happyness-poster.jpg',
        '/the-pursuit-of-happyness-backdrop.jpg',
        'Gabriele Muccino',
        'Don''t ever let somebody tell you, you can''t do something.',
        86,
        '1h 57m',
        'A struggling salesman takes custody of his son as he begins a life-changing professional career, navigating homelessness while pursuing an unpaid internship at a brokerage firm.'
    ),
    (
        36,
        'movie',
        'The Drama',
        2026,
        7.0,
        75,
        '["Comedy","Drama","Romance"]',
        '/the-drama-poster.jpg',
        '/the-drama-backdrop.jpg',
        'Kristoffer Borgli',
        'Some stories are better left untold.',
        60,
        '1h 33m',
        'Emma and Charlie are a happily engaged couple just days from their wedding when an unexpected revelation puts their relationship to the test.'
    ),
    (
        37,
        'movie',
        'Dunkirk',
        2017,
        7.8,
        92,
        '["Action","Drama","History","War"]',
        '/dunkirk-poster.jpg',
        '/dunkirk-backdrop.jpg',
        'Christopher Nolan',
        'Survival is victory.',
        89,
        '1h 46m',
        'Allied soldiers from Belgium, the British Empire, Canada, and France are surrounded by the German Army and evacuated during a fierce battle in World War II.'
    ),
    (
        38,
        'movie',
        'We Live in Time',
        2024,
        7.2,
        73,
        '["Comedy","Drama","Romance"]',
        '/we-live-in-time-poster.jpg',
        '/we-live-in-time-backdrop.jpg',
        'John Crowley',
        'Make every moment count.',
        78,
        '1h 47m',
        'Almut and Tobias'' lives are told in a non-linear narrative, weaving through their relationship, parenthood, and Almut''s battle with cancer.'
    ),
    (
        39,
        'movie',
        'Hacksaw Ridge',
        2016,
        8.1,
        86,
        '["Biography","Drama","History","War"]',
        '/hacksaw-ridge-poster.jpg',
        '/hacksaw-ridge-backdrop.jpg',
        'Mel Gibson',
        'The true story of conscientious objector Desmond Doss.',
        88,
        '2h 19m',
        'World War II American Army medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.'
    ),
    (
        40,
        'movie',
        '18x2: Beyond Youthful Days',
        2024,
        7.6,
        80,
        '["Drama","Romance"]',
        '/18x2-beyond-youthful-days-poster.jpg',
        '/18x2-beyond-youthful-days-backdrop.jpg',
        'Michihito Fujii',
        'A journey that traces back the memory of their first love from 18 years ago.',
        75,
        '2h 4m',
        'Having lost his job and the company he built, a 36-year-old man at rock bottom goes on a wistful solo trip to Japan in search of the love he left behind nearly two decades ago.'
    ),
    (
        41,
        'movie',
        'The Last 10 Years',
        2022,
        7.1,
        78,
        '["Drama","Romance"]',
        '/the-last-10-years-poster.jpg',
        '/the-last-10-years-backdrop.jpg',
        'Michihito Fujii',
        'A love story with a deadline.',
        73,
        '2h 4m',
        'Twenty-year-old Matsuri Takabayashi learns she only has ten years to live due to an incurable disease and decides not to fall in love, until she meets Kazuto Manabe at a school reunion.'
    ),
    (
        42,
        'movie',
        'The Notebook',
        2004,
        7.8,
        53,
        '["Drama","Romance"]',
        '/the-notebook-poster.jpg',
        '/the-notebook-backdrop.jpg',
        'Nick Cassavetes',
        'Behind every great love is a great story.',
        90,
        '2h 3m',
        'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are soon separated by her social-climbing parents.'
    ),
    (
        43,
        'movie',
        'Atonement',
        2007,
        7.9,
        83,
        '["Drama","Mystery","Romance"]',
        '/atonement-poster.jpg',
        '/atonement-backdrop.jpg',
        'Joe Wright',
        'A childhood mistake. A lifetime to pay for it.',
        81,
        '2h 3m',
        'Thirteen-year-old fledgling writer Briony Tallis irrevocably changes the course of several lives when she accuses her older sister''s lover of a crime he did not commit.'
    ),
    (
        44,
        'movie',
        'Before Sunrise',
        1995,
        8.1,
        100,
        '["Drama","Romance"]',
        '/before-sunrise-poster.jpg',
        '/before-sunrise-backdrop.jpg',
        'Richard Linklater',
        'A romance based entirely on chance.',
        82,
        '1h 41m',
        'A young man and woman meet on a train in Europe and spend one evening together in Vienna before they have to part ways the next morning.'
    ),
    (
        45,
        'movie',
        'The Dark Knight',
        2008,
        9.0,
        94,
        '["Action","Crime","Drama"]',
        '/the-dark-knight-poster.jpg',
        '/the-dark-knight-backdrop.jpg',
        'Christopher Nolan',
        'Why so serious?',
        99,
        '2h 32m',
        'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.'
    ),
    (
        46,
        'movie',
        '500 Days of Summer',
        2009,
        7.7,
        86,
        '["Comedy","Drama","Romance"]',
        '/500-days-of-summer-poster.jpg',
        '/500-days-of-summer-backdrop.jpg',
        'Marc Webb',
        'This is not a love story. This is a story about love.',
        85,
        '1h 35m',
        'An offbeat romantic comedy about a woman who doesn''t believe true love exists, and the young man who falls for her, told in a non-linear narrative across 500 days of their relationship.'
    ),
    (
        47,
        'movie',
        'Five Feet Apart',
        2019,
        7.2,
        32,
        '["Drama","Romance"]',
        '/five-feet-apart-poster.jpg',
        '/five-feet-apart-backdrop.jpg',
        'Justin Baldoni',
        'Every moment counts.',
        78,
        '1h 56m',
        'Two teenagers with cystic fibrosis meet in a hospital and fall in love, but their condition forces them to stay at least six feet apart at all times to avoid infecting each other.'
    ),
    (
        48,
        'movie',
        'Inception',
        2010,
        8.8,
        87,
        '["Action","Adventure","Sci-Fi","Thriller"]',
        '/inception-poster.jpg',
        '/inception-backdrop.jpg',
        'Christopher Nolan',
        'Your mind is the scene of the crime.',
        97,
        '2h 28m',
        'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO, but a dark secret of his own threatens to derail everything.'
    ),
    (
        49,
        'movie',
        'Ghosted',
        2023,
        6.2,
        24,
        '["Action","Comedy","Romance"]',
        '/ghosted-poster.jpg',
        '/ghosted-backdrop.jpg',
        'Dexter Fletcher',
        'It''s a date... or is it a mission?',
        65,
        '2h 0m',
        'Cole falls head over heels for the mysterious Sadie, but quickly discovers that getting ghosted by the woman of his dreams is just the beginning, when he finds out she is actually a notorious spy.'
    ),
    (
        50,
        'movie',
        'No Time to Die',
        2021,
        7.3,
        84,
        '["Action","Adventure","Thriller"]',
        '/no-time-to-die-poster.jpg',
        '/no-time-to-die-backdrop.jpg',
        'Cary Joji Fukunaga',
        'No time to live. No time to trust. No time to die.',
        93,
        '2h 43m',
        'James Bond has left active service when his friend Felix Leiter from the CIA enlists his help, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.'
    ),
    (
        51,
        'movie',
        'The Conjuring: Last Rites',
        2025,
        6.2,
        55,
        '["Horror","Mystery","Thriller"]',
        '/the-conjuring-last-rites-poster.jpg',
        '/the-conjuring-last-rites-backdrop.jpg',
        'Michael Chaves',
        'Their final case.',
        90,
        '2h 15m',
        'Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities with ties to their very first encounter together.'
    ),
    (
        52,
        'movie',
        'Hamnet',
        2025,
        7.9,
        90,
        '["Biography","Drama","History"]',
        '/hamnet-poster.jpg',
        '/hamnet-backdrop.jpg',
        'Chloé Zhao',
        'The love story that inspired a masterpiece.',
        86,
        '2h 6m',
        'In 16th-century England, William Shakespeare and his wife Agnes grapple with grief after the death of their young son Hamnet, in a story that shaped the creation of Hamlet.'
    ),
    (
        53,
        'movie',
        'Jerry Maguire',
        1996,
        7.6,
        81,
        '["Comedy","Drama","Romance"]',
        '/jerry-maguire-poster.jpg',
        '/jerry-maguire-backdrop.jpg',
        'Cameron Crowe',
        'The Sports Agency has a new mission statement.',
        80,
        '2h 19m',
        'A sports agent has a moral epiphany and is fired after writing it down, leading him to start his own agency with only one client willing to stick with him.'
    ),
    (
        54,
        'movie',
        'Fight Club',
        1999,
        8.8,
        79,
        '["Drama"]',
        '/fight-club-poster.jpg',
        '/fight-club-backdrop.jpg',
        'David Fincher',
        'Mischief. Mayhem. Soap.',
        96,
        '2h 19m',
        'An insomniac office worker and a soap salesman form an underground fight club that evolves into something much more dangerous.'
    ),
    (
        55,
        'movie',
        'Forrest Gump',
        1994,
        8.8,
        71,
        '["Drama","Romance"]',
        '/forrest-gump-poster.jpg',
        '/forrest-gump-backdrop.jpg',
        'Robert Zemeckis',
        'Life is like a box of chocolates... you never know what you''re gonna get.',
        95,
        '2h 22m',
        'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with a low IQ but a kind heart.'
    ),
    (
        56,
        'movie',
        'Your Name',
        2016,
        8.4,
        96,
        '["Animation","Drama","Fantasy","Romance"]',
        '/your-name-poster.jpg',
        '/your-name-backdrop.jpg',
        'Makoto Shinkai',
        'Your name is what I want to know.',
        94,
        '1h 46m',
        'Two teenagers, a boy in Tokyo and a girl in the countryside, begin to swap bodies mysteriously and grow connected, until a comet threatens to keep them apart forever.'
    ),
    (
        57,
        'movie',
        'The Pianist',
        2002,
        8.5,
        95,
        '["Biography","Drama","War"]',
        '/the-pianist-poster.jpg',
        '/the-pianist-backdrop.jpg',
        'Roman Polanski',
        'Music was his passion. Survival was his masterpiece.',
        92,
        '2h 30m',
        'A Polish Jewish pianist struggles to survive the destruction of the Warsaw ghetto during World War II by hiding among the ruins of the city.'
    ),
    (
        58,
        'movie',
        'Star Wars: Episode III - Revenge of the Sith',
        2005,
        7.5,
        80,
        '["Action","Adventure","Fantasy","Sci-Fi"]',
        '/star-wars-revenge-of-the-sith-poster.jpg',
        '/star-wars-revenge-of-the-sith-backdrop.jpg',
        'George Lucas',
        'The saga is complete.',
        90,
        '2h 20m',
        'As the Clone Wars rage, Anakin Skywalker is seduced by the dark side of the Force and becomes the evil Sith lord Darth Vader.'
    ),
    (
        59,
        'movie',
        'Interstellar',
        2014,
        8.7,
        73,
        '["Adventure","Drama","Sci-Fi"]',
        '/interstellar-poster.jpg',
        '/interstellar-backdrop.jpg',
        'Christopher Nolan',
        'Mankind was born on Earth. It was never meant to die here.',
        96,
        '2h 49m',
        'A team of explorers travels through a wormhole in space in an attempt to ensure humanity''s survival as Earth becomes uninhabitable.'
    ),
    (
        60,
        'movie',
        'Love & Other Drugs',
        2010,
        6.6,
        47,
        '["Comedy","Drama","Romance"]',
        '/love-and-other-drugs-poster.jpg',
        '/love-and-other-drugs-backdrop.jpg',
        'Edward Zwick',
        'Get ready for a major rush.',
        70,
        '1h 52m',
        'A drug rep''s relationship with an artist who has Parkinson''s disease takes both of them by surprise as they navigate love and vulnerability.'
    ),
    (
        61,
        'movie',
        'Knives Out',
        2019,
        7.9,
        97,
        '["Comedy","Crime","Drama","Mystery"]',
        '/knives-out-poster.jpg',
        '/knives-out-backdrop.jpg',
        'Rian Johnson',
        'Hold on to your subscriptions.',
        92,
        '2h 10m',
        'A detective investigates the death of a patriarch of an eccentric, combative family at his estate, with a complex web of secrets and suspects.'
    ),
    (
        62,
        'movie',
        'John Wick: Chapter 2',
        2017,
        7.4,
        89,
        '["Action","Crime","Thriller"]',
        '/john-wick-chapter-2-poster.jpg',
        '/john-wick-chapter-2-backdrop.jpg',
        'Chad Stahelski',
        'Never stab the devil in the back.',
        88,
        '2h 2m',
        'John Wick is forced back into the assassin underworld to repay a debt, leading him on a globe-trotting journey against some of the world''s deadliest killers.'
    ),
    (
        63,
        'movie',
        'Call Me by Your Name',
        2017,
        7.9,
        91,
        '["Drama","Romance"]',
        '/call-me-by-your-name-poster.jpg',
        '/call-me-by-your-name-backdrop.jpg',
        'Luca Guadagnino',
        'Every name has a story.',
        87,
        '2h 12m',
        'In 1980s Italy, a romance blossoms between a seventeen-year-old boy and a visiting graduate student over the course of an unforgettable summer.'
    ),
    (
        64,
        'movie',
        'Eternal Sunshine of the Spotless Mind',
        2004,
        8.3,
        92,
        '["Drama","Romance","Sci-Fi"]',
        '/eternal-sunshine-of-the-spotless-mind-poster.jpg',
        '/eternal-sunshine-of-the-spotless-mind-backdrop.jpg',
        'Michel Gondry',
        'You can erase someone from your mind. Getting them out of your heart is another story.',
        89,
        '1h 48m',
        'After a painful breakup, Joel discovers his ex-girlfriend underwent a procedure to erase him from her memory, and decides to do the same, only to find their memories worth fighting for.'
    ),
    (
        65,
        'movie',
        'Mad Max: Fury Road',
        2015,
        8.1,
        97,
        '["Action","Adventure","Sci-Fi"]',
        '/mad-max-fury-road-poster.jpg',
        '/mad-max-fury-road-backdrop.jpg',
        'George Miller',
        'What a lovely day.',
        93,
        '2h 0m',
        'In a post-apocalyptic wasteland, Max teams up with a rebellious warrior named Furiosa to flee from a tyrannical ruler and his army in search of a sanctuary.'
    ),
    (
        66,
        'movie',
        'Chainsaw Man: The Movie – Reze Arc',
        2025,
        8.3,
        88,
        '["Animation","Action","Adventure","Horror"]',
        '/chainsaw-man-reze-arc-poster.jpg',
        '/chainsaw-man-reze-arc-backdrop.jpg',
        'Tatsuya Yoshihara',
        'Fueled by love in a world where survival knows no rules.',
        91,
        '1h 40m',
        'A mysterious girl named Reze steps into Denji''s world, forcing him into his deadliest battle yet as devils, hunters, and secret enemies collide in a brutal war.'
    ),
    (
        67,
        'tv',
        'Breaking Bad',
        2008,
        9.5,
        99,
        '["Drama","Crime","Thriller"]',
        '/breaking-bad-poster.jpg',
        '/breaking-bad-backdrop.jpg',
        'Vince Gilligan',
        'All Hail the King.',
        99,
        '5 Seasons',
        'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student to secure his family''s future.'
    ),
    (
        68,
        'tv',
        'Better Call Saul',
        2015,
        9.0,
        97,
        '["Drama","Crime","Thriller"]',
        '/better-call-saul-poster.jpg',
        '/better-call-saul-backdrop.jpg',
        'Vince Gilligan',
        'Everyone deserves a second chance.',
        95,
        '6 Seasons',
        'The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful meeting with Walter White.'
    ),
    (
        69,
        'tv',
        'Game of Thrones',
        2011,
        9.2,
        89,
        '["Drama","Fantasy","Action"]',
        '/game-of-thrones-poster.jpg',
        '/game-of-thrones-backdrop.jpg',
        'David Benioff',
        'Winter is coming.',
        99,
        '8 Seasons',
        'Nine noble families fight for control of the mythical land of Westeros, while an ancient enemy returns after being dormant for millennia.'
    ),
    (
        70,
        'tv',
        'House of the Dragon',
        2022,
        8.4,
        92,
        '["Drama","Fantasy","Action"]',
        '/house-of-the-dragon-poster.jpg',
        '/house-of-the-dragon-backdrop.jpg',
        'Ryan Condal',
        'The realm was never ready.',
        94,
        '2 Seasons',
        'The story of House Targaryen, set 200 years before the events of Game of Thrones, chronicling the violent succession war that tore the dynasty apart.'
    ),
    (
        71,
        'tv',
        'The Boys',
        2019,
        8.7,
        85,
        '["Action","Comedy","Drama","Sci-Fi"]',
        '/the-boys-poster.jpg',
        '/the-boys-backdrop.jpg',
        'Eric Kripke',
        'The supes are not heroes.',
        96,
        '4 Seasons',
        'A group of vigilantes sets out to take down corrupt superheroes who abuse their powers, while a powerful corporation works to cover up their crimes.'
    ),
    (
        72,
        'tv',
        'Stranger Things',
        2016,
        8.7,
        90,
        '["Drama","Fantasy","Horror","Sci-Fi"]',
        '/stranger-things-poster.jpg',
        '/stranger-things-backdrop.jpg',
        'The Duffer Brothers',
        'Every ending has a beginning.',
        97,
        '5 Seasons',
        'When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces and secret government exploits in order to get him back.'
    ),
    (
        73,
        'tv',
        'Dark',
        2017,
        8.8,
        95,
        '["Drama","Mystery","Sci-Fi","Thriller"]',
        '/dark-poster.jpg',
        '/dark-backdrop.jpg',
        'Baran bo Odar',
        'The beginning is the end.',
        90,
        '3 Seasons',
        'A family saga with a supernatural twist set in a German town where the disappearance of two young children exposes the fractured relationships among four families across multiple time periods.'
    ),
    (
        74,
        'tv',
        'Peaky Blinders',
        2013,
        8.8,
        93,
        '["Crime","Drama","History"]',
        '/peaky-blinders-poster.jpg',
        '/peaky-blinders-backdrop.jpg',
        'Steven Knight',
        'He''s not a gangster. He''s a businessman.',
        95,
        '6 Seasons',
        'A gangster family epic set in 1919 Birmingham, England, centering on the Peaky Blinders gang and their ambitious leader Tommy Shelby.'
    ),
    (
        75,
        'tv',
        'True Detective',
        2014,
        9.0,
        94,
        '["Crime","Drama","Mystery","Thriller"]',
        '/true-detective-poster.jpg',
        '/true-detective-backdrop.jpg',
        'Nic Pizzolatto',
        'Touch darkness and darkness touches you back.',
        92,
        '4 Seasons',
        'An anthology crime drama series where each season follows a new investigation and new cast, exploring the philosophical depths of crime and punishment.'
    ),
    (
        76,
        'tv',
        'Money Heist',
        2017,
        8.2,
        57,
        '["Action","Crime","Drama","Thriller"]',
        '/money-heist-poster.jpg',
        '/money-heist-backdrop.jpg',
        'Álex Pina',
        'Resistance is justified.',
        94,
        '5 Seasons',
        'A criminal mastermind who goes by "The Professor" recruits eight robbers to carry out an ambitious plan to rob the Royal Mint of Spain, holding hostages as leverage.'
    ),
    (
        77,
        'tv',
        'Sherlock',
        2010,
        9.1,
        87,
        '["Crime","Drama","Mystery","Thriller"]',
        '/sherlock-poster.jpg',
        '/sherlock-backdrop.jpg',
        'Mark Gatiss',
        'The game is on.',
        93,
        '4 Seasons',
        'A modern update of the classic Arthur Conan Doyle stories, following the brilliant consulting detective Sherlock Holmes and his partner Dr. John Watson in 21st century London.'
    ),
    (
        78,
        'tv',
        'Friends',
        1994,
        8.9,
        82,
        '["Comedy","Romance"]',
        '/friends-poster.jpg',
        '/friends-backdrop.jpg',
        'David Crane',
        'I''ll be there for you.',
        98,
        '10 Seasons',
        'Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.'
    ),
    (
        79,
        'tv',
        'The Office',
        2005,
        9.0,
        81,
        '["Comedy"]',
        '/the-office-poster.jpg',
        '/the-office-backdrop.jpg',
        'Greg Daniels',
        'A documentary about the everyday lives of office employees.',
        96,
        '9 Seasons',
        'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium, all centered around clueless regional manager Michael Scott.'
    ),
    (
        80,
        'tv',
        'How I Met Your Mother',
        2005,
        8.3,
        83,
        '["Comedy","Romance"]',
        '/himym-poster.jpg',
        '/himym-backdrop.jpg',
        'Carter Bays',
        'This is going to be legen... wait for it... dary.',
        90,
        '9 Seasons',
        'A father recounts to his children, through a series of flashbacks, the journey he and his four best friends took leading up to him meeting their mother.'
    ),
    (
        81,
        'tv',
        'Euphoria',
        2019,
        8.4,
        81,
        '["Drama"]',
        '/euphoria-poster.jpg',
        '/euphoria-backdrop.jpg',
        'Sam Levinson',
        'We are all searching for something.',
        92,
        '3 Seasons',
        'A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.'
    ),
    (
        82,
        'tv',
        'Chernobyl',
        2019,
        9.4,
        96,
        '["Drama","History","Thriller"]',
        '/chernobyl-poster.jpg',
        '/chernobyl-backdrop.jpg',
        'Johan Renck',
        'What is the cost of lies?',
        96,
        '1 Season',
        'In April 1986, an explosion at the Chernobyl nuclear power plant in the USSR becomes one of the world''s worst man-made catastrophes. This miniseries dramatizes the true story of the disaster and its aftermath.'
    ),
    (
        83,
        'tv',
        'Mindhunter',
        2017,
        8.6,
        97,
        '["Crime","Drama","Thriller"]',
        '/mindhunter-poster.jpg',
        '/mindhunter-backdrop.jpg',
        'David Fincher',
        'Inside the minds of madness.',
        88,
        '2 Seasons',
        'In the late 1970s two FBI agents expand criminal science by delving into the psychology of murder and getting unparalleled access to the country''s most notorious serial killers.'
    ),
    (
        84,
        'tv',
        'Narcos',
        2015,
        8.8,
        89,
        '["Biography","Crime","Drama","Thriller"]',
        '/narcos-poster.jpg',
        '/narcos-backdrop.jpg',
        'Carlo Bernard',
        'The business of crime.',
        91,
        '3 Seasons',
        'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.'
    ),
    (
        85,
        'tv',
        'Invincible',
        2021,
        8.7,
        96,
        '["Animation","Action","Adventure","Drama","Sci-Fi"]',
        '/invincible-poster.jpg',
        '/invincible-backdrop.jpg',
        'Robert Kirkman',
        'What does it take to be a hero?',
        93,
        '3 Seasons',
        'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own.'
    ),
    (
        86,
        'tv',
        'Cyberpunk: Edgerunners',
        2022,
        8.3,
        96,
        '["Animation","Action","Drama","Sci-Fi"]',
        '/cyberpunk-edgerunners-poster.jpg',
        '/cyberpunk-edgerunners-backdrop.jpg',
        'Hiroyuki Imaishi',
        'Live fast, die pretty.',
        90,
        '1 Season',
        'A street kid tries to survive in a technology and body modification-obsessed city of the future, eventually becoming an outlaw mercenary known as an Edgerunner.'
    ),
    (
        87,
        'tv',
        'The Sopranos',
        1999,
        9.2,
        97,
        '["Crime","Drama"]',
        '/the-sopranos-poster.jpg',
        '/the-sopranos-backdrop.jpg',
        'David Chase',
        'Family. Redefined.',
        97,
        '6 Seasons',
        'New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life, seeking help from psychiatrist Dr. Jennifer Melfi.'
    ),
    (
        88,
        'tv',
        'Normal People',
        2020,
        8.0,
        93,
        '["Drama","Romance"]',
        '/normal-people-poster.jpg',
        '/normal-people-backdrop.jpg',
        'Lenny Abrahamson',
        'The story of two people who bring out the best and worst in each other.',
        82,
        '1 Season',
        'Connell and Marianne grow up in the same small town in the west of Ireland but are worlds apart. At school, Connell is popular and well-liked, while Marianne is a loner.'
    ),
    (
        89,
        'tv',
        'The Witcher',
        2019,
        8.0,
        69,
        '["Action","Adventure","Drama","Fantasy"]',
        '/the-witcher-poster.jpg',
        '/the-witcher-backdrop.jpg',
        'Lauren Schmidt Hissrich',
        'Evil is evil.',
        88,
        '4 Seasons',
        'Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.'
    ),
    (
        90,
        'tv',
        'It: Welcome to Derry',
        2024,
        7.8,
        72,
        '["Drama","Horror","Mystery"]',
        '/it-welcome-to-derry-poster.jpg',
        '/it-welcome-to-derry-backdrop.jpg',
        'Andy Muschietti',
        'Derry has always been hungry.',
        80,
        '1 Season',
        'A prequel series set in the 1960s exploring the origins of Pennywise the Dancing Clown and the dark history of Derry, Maine, decades before the events of the original story.'
    ),
    (
        91,
        'tv',
        'The Walking Dead',
        2010,
        8.1,
        80,
        '["Drama","Horror","Thriller"]',
        '/the-walking-dead-poster.jpg',
        '/the-walking-dead-backdrop.jpg',
        'Frank Darabont',
        'Fight the dead. Fear the living.',
        91,
        '11 Seasons',
        'Sheriff''s deputy Rick Grimes wakes up from a coma to find a post-apocalyptic world dominated by flesh-eating zombies and must lead a group of survivors to safety.'
    ),
    (
        92,
        'tv',
        'Prison Break',
        2005,
        8.3,
        60,
        '["Action","Crime","Drama","Mystery","Thriller"]',
        '/prison-break-poster.jpg',
        '/prison-break-backdrop.jpg',
        'Paul Scheuring',
        'Break out or die trying.',
        89,
        '5 Seasons',
        'A man is sent to a maximum-security prison housing his brother, who has been condemned to death for a crime he did not commit. Determined to free his brother, he engineers an elaborate plan to break them both out.'
    ),
    (
        93,
        'tv',
        'Dexter',
        2006,
        8.6,
        80,
        '["Crime","Drama","Mystery","Thriller"]',
        '/dexter-poster.jpg',
        '/dexter-backdrop.jpg',
        'James Manos Jr.',
        'Justice has a dark side.',
        88,
        '9 Seasons',
        'Dexter Morgan, a blood spatter analyst for the Miami Metro Police, lives a secret double life as a serial killer who targets other killers.'
    ),
    (
        94,
        'tv',
        'Squid Game',
        2021,
        8.0,
        95,
        '["Action","Drama","Mystery","Thriller"]',
        '/squid-game-poster.jpg',
        '/squid-game-backdrop.jpg',
        'Hwang Dong-hyuk',
        'Desperately seeking wealth. Blindly following rules.',
        98,
        '2 Seasons',
        'Hundreds of cash-strapped players accept a strange invitation to compete in children''s games. Inside, a tempting prize awaits with deadly stakes.'
    ),
    (
        95,
        'tv',
        'The Queen''s Gambit',
        2020,
        8.6,
        96,
        '["Drama"]',
        '/the-queens-gambit-poster.jpg',
        '/the-queens-gambit-backdrop.jpg',
        'Scott Frank',
        'Her game. Her rules.',
        92,
        '1 Season',
        'Orphaned at the age of nine, prodigious introvert Beth Harmon discovers and masters the game of chess in 1950s USA. But the gambit of her success is a perilous one, as she grapples with addiction in a man''s world.'
    ),
    (
        96,
        'tv',
        'Wednesday',
        2022,
        8.1,
        68,
        '["Comedy","Fantasy","Horror","Mystery"]',
        '/wednesday-poster.jpg',
        '/wednesday-backdrop.jpg',
        'Tim Burton',
        'She''s dying to fit in.',
        91,
        '2 Seasons',
        'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends and enemies at Nevermore Academy.'
    ),
    (
        97,
        'tv',
        'A Good Girl''s Guide to Murder',
        2024,
        7.8,
        88,
        '["Crime","Drama","Mystery","Thriller"]',
        '/a-good-girls-guide-to-murder-poster.jpg',
        '/a-good-girls-guide-to-murder-backdrop.jpg',
        'Bail Bryce',
        'Everyone has something to hide.',
        85,
        '1 Season',
        'Five years after the murder of teenager Andie Bell, student Pippa Fitz-Amobi reopens the case for her school project, convinced that the accused killer Sal Singh was innocent.'
    ),
    (
        98,
        'tv',
        'Vikings',
        2013,
        8.5,
        88,
        '["Action","Drama","History","War"]',
        '/vikings-poster.jpg',
        '/vikings-backdrop.jpg',
        'Michael Hirst',
        'The legends are true.',
        88,
        '6 Seasons',
        'The historical drama follows the legendary Norse hero Ragnar Lothbrok on his rise from humble farmer to fearsome Viking raider and, eventually, king.'
    ),
    (
        99,
        'tv',
        'Anne with an E',
        2017,
        8.6,
        78,
        '["Drama","Family","Romance"]',
        '/anne-with-an-e-poster.jpg',
        '/anne-with-an-e-backdrop.jpg',
        'Moira Walley-Beckett',
        'Find your place in the world.',
        82,
        '3 Seasons',
        'A young orphan girl, Anne Shirley, comes to live with an aging brother and sister on their farm on Prince Edward Island, winning them over with her spirited personality and vivid imagination.'
    ),
    (
        100,
        'tv',
        'You',
        2018,
        7.7,
        88,
        '["Drama","Romance","Thriller"]',
        '/you-poster.jpg',
        '/you-backdrop.jpg',
        'Greg Berlanti',
        'Love can be dangerous.',
        89,
        '4 Seasons',
        'A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.'
    ),
    (
        101,
        'tv',
        'The Crown',
        2016,
        8.6,
        88,
        '["Biography","Drama","History"]',
        '/the-crown-poster.jpg',
        '/the-crown-backdrop.jpg',
        'Peter Morgan',
        'The price of power.',
        87,
        '6 Seasons',
        'Follows the political rivalries and romance of Queen Elizabeth II''s reign and the events that shaped the second half of the twentieth century.'
    ),
    (
        102,
        'tv',
        'Riverdale',
        2017,
        6.6,
        63,
        '["Crime","Drama","Mystery"]',
        '/riverdale-poster.jpg',
        '/riverdale-backdrop.jpg',
        'Roberto Aguirre-Sacasa',
        'Small town. Dark secrets.',
        80,
        '7 Seasons',
        'While navigating the complexities of romance, school, and family, Archie and his friends search for answers about the dark events that take place in the town of Riverdale.'
    ),
    (
        103,
        'tv',
        'Sex Education',
        2019,
        8.3,
        93,
        '["Comedy","Drama"]',
        '/sex-education-poster.jpg',
        '/sex-education-backdrop.jpg',
        'Laurie Nunn',
        'Growing up is complicated.',
        88,
        '4 Seasons',
        'A socially awkward teenager with a sex therapist mother teams up with a rebellious classmate to set up an underground sex therapy clinic at school.'
    ),
    (
        104,
        'tv',
        'Gossip Girl',
        2007,
        7.4,
        82,
        '["Drama","Romance"]',
        '/gossip-girl-poster.jpg',
        '/gossip-girl-backdrop.jpg',
        'Josh Schwartz',
        'You know you love me.',
        85,
        '6 Seasons',
        'Privileged teenagers attending elite private schools in Manhattan''s Upper East Side have their scandalous lives chronicled by an all-knowing anonymous blogger known as Gossip Girl.'
    ),
    (
        105,
        'tv',
        'The End of the F***ing World',
        2017,
        8.0,
        96,
        '["Adventure","Comedy","Crime","Drama"]',
        '/the-end-of-the-fing-world-poster.jpg',
        '/the-end-of-the-fing-world-backdrop.jpg',
        'Jonathan Entwistle',
        'A love story. Kind of.',
        83,
        '2 Seasons',
        'James, a 17-year-old who believes he is a psychopath, and Alyssa, a rebellious classmate, go on the run together across England, getting into increasingly dangerous situations.'
    ),
    (
        106,
        'tv',
        'Supernatural',
        2005,
        8.4,
        69,
        '["Drama","Fantasy","Horror","Mystery"]',
        '/supernatural-poster.jpg',
        '/supernatural-backdrop.jpg',
        'Eric Kripke',
        'Saving people. Hunting things. The family business.',
        88,
        '15 Seasons',
        'Two brothers follow their father''s footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.'
    ),
    (
        107,
        'tv',
        'Chainsaw Man',
        2022,
        8.5,
        96,
        '["Animation","Action","Horror","Drama"]',
        '/chainsaw-man-poster.jpg',
        '/chainsaw-man-backdrop.jpg',
        'Ryû Nakayama',
        'The city will run red.',
        91,
        '1 Season',
        'Denji, a young man deeply in debt, merges with his devil-dog Pochita to become Chainsaw Man after being betrayed and killed by the yakuza. Now working as a Devil Hunter for a government agency, he pursues simple dreams in a world overrun by devils.'
    );

-- ─── SEED: REVIEWS ───────────────────────────────────────────
-- FIX: All likes_count values set to 0 (were fake seeded values: 142, 389, 201, etc.)
INSERT IGNORE INTO
    reviews (
        id,
        movie_id,
        user_id,
        rating,
        text,
        mood,
        quote,
        is_spoiler,
        likes_count
    )
VALUES (
        1,
        1,
        1,
        5,
        'Denis Villeneuve has crafted an absolute masterpiece. The scale is breathtaking — every frame feels like a painting. Zendaya and Chalamet deliver career-best performances. The sound design alone deserves every award it can get.',
        'Epic',
        'Power over spice is power over all.',
        0,
        0
    ),
    (
        2,
        2,
        2,
        5,
        'Three hours that feel like twenty minutes. Nolan somehow made theoretical physics viscerally thrilling. Cillian Murphy disappears into the role completely. The IMAX sequences are unlike anything I have ever seen in a cinema.',
        'Mind-bending',
        'Now I am become Death, the destroyer of worlds.',
        0,
        0
    ),
    (
        3,
        9,
        3,
        5,
        'An absolute visual triumph. This film should not work — it has like 6 different animation styles — but it is the most coherent and emotionally resonant animated film I have seen in years. Miles Morales is a generational character.',
        'Epic',
        'Everyone keeps telling me how my story is supposed to go.',
        0,
        0
    ),
    (
        4,
        5,
        4,
        4,
        'Lanthimos at his most accessible. Emma Stone is simply extraordinary. The film philosophy on freedom and societal norms takes time to unpack, but it is worth every frame.',
        'Thought-provoking',
        'I will not be subjugated by cruel rule.',
        0,
        0
    ),
    (
        5,
        13,
        5,
        4,
        'Provocative and genuinely unsettling. Barry Keoghan gives a career-defining performance. The final sequence is completely unforgettable and I have not stopped thinking about it.',
        'Terrifying',
        'I am just a middle-class boy from a comprehensive.',
        1,
        0
    ),
    (
        6,
        6,
        1,
        5,
        'The most quietly devastating film of the year. Celine Song debut is extraordinarily assured — a meditation on the lives we live and the ones we leave behind. I cried three times.',
        'Heartwarming',
        'In-yun. It is providence.',
        0,
        0
    ),
    (
        7,
        7,
        2,
        5,
        'The greatest finale in television history. Every performance is career-defining. The boardroom scene alone is worth every second of four seasons of television.',
        'Mind-bending',
        'I love you but you are not kind.',
        1,
        0
    ),
    (
        8,
        12,
        3,
        5,
        'Rarely does a video game adaptation understand its source material so deeply. Pedro Pascal and Bella Ramsey are exceptional. Episode 3 alone is a masterpiece of television storytelling.',
        'Heartwarming',
        'You should smile more.',
        0,
        0
    ),
    (
        9,
        14,
        4,
        4,
        'Greta Gerwig somehow turned a toy commercial into a sharp feminist critique. Margot Robbie is perfect. Ryan Gosling steals every single scene he is in.',
        'Inspiring',
        'Do you guys ever think about dying?',
        0,
        0
    ),
    (
        10,
        8,
        5,
        4,
        'Scorsese meditation on American greed and complicity is his most morally complex film since Goodfellas. The length is completely justified. Robert De Niro is genuinely haunting throughout.',
        'Thought-provoking',
        'We are the bad guys.',
        0,
        0
    );

-- ─── SEED: DISCUSSIONS ───────────────────────────────────────
-- FIX: likes_count, views, and replies all set to 0 (were fake seeded values)
INSERT IGNORE INTO
    discussions (
        id,
        user_id,
        title,
        body,
        tags,
        likes_count,
        views,
        replies
    )
VALUES (
        1,
        2,
        'Is Oppenheimer the best biopic ever made?',
        'Nolan somehow turned a history lesson into a visceral thriller. The non-linear structure mirrors Oppenheimer fractured sense of morality. Has any biopic ever been this formally ambitious?',
        '["Oppenheimer","Nolan","Biopic"]',
        0,
        0,
        0
    ),
    (
        2,
        3,
        'Why Dune: Part Two is a generational sci-fi achievement',
        'Villeneuve did not just adapt Herbert — he reinvented what blockbuster filmmaking can be. Every frame is a painting. The sound design alone deserves awards season recognition.',
        '["Dune","Sci-Fi","Villeneuve"]',
        0,
        0,
        0
    ),
    (
        3,
        1,
        'Succession finale: did it stick the landing?',
        'Hot take: the Waystar boardroom scene is the finest 20 minutes in television history. The performances, the silence, the final shot — perfection. Change my mind.',
        '["Succession","TV","Drama"]',
        0,
        0,
        0
    ),
    (
        4,
        4,
        'The Bear Season 3 — was the hype justified?',
        'Season 2 set an impossible bar. Season 3 is quieter, more introspective. Some call it slow, I call it mature. The episode Napkins alone is worth the price of admission.',
        '["TheBear","TV","Drama"]',
        0,
        0,
        0
    ),
    (
        5,
        5,
        'Past Lives deserved the Best Picture Oscar',
        'The Academy consistently undervalues quiet, personal cinema. Past Lives is the rare film that makes you feel the weight of unlived lives. Celine Song is a generational voice.',
        '["PastLives","Oscars","Romance"]',
        0,
        0,
        0
    );

-- ─── Done! ────────────────────────────────────────────────────
-- Your database is ready with:
--   5 users  |  18 movies  |  10 reviews  |  5 discussions
-- Login with any seeded user email + password: password123
-- e.g.: jobayer123@gmail.com / password123

-- ─── Image Updates (run if DB already existed) ────────────────
UPDATE movies
SET
    poster = '/dune-part-two-poster.jpg',
    backdrop = '/dune-part-two-backdrop.jpg'
WHERE
    id = 1;

-- ─── ADMIN TABLES (run after initial schema) ─────────────────

-- Admin accounts table
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin account — password: Tajin007!
INSERT IGNORE INTO
    admins (
        first_name,
        last_name,
        email,
        password_hash
    )
VALUES (
        'Tajin Ahmed',
        'Mahin',
        'tajinahmed007@gmail.com',
        '$2a$10$FZ0UU4Dwk0VqAhW1QwgqN.hwk2xJWKHLGfEkBfW2pKTB/DBWYCzGa'
    );

-- Add moderation columns to users
ALTER TABLE users
ADD COLUMN IF NOT EXISTS is_banned TINYINT DEFAULT 0,
ADD COLUMN IF NOT EXISTS is_muted TINYINT DEFAULT 0;

-- Add report column to reviews
ALTER TABLE reviews
ADD COLUMN IF NOT EXISTS reported TINYINT DEFAULT 0;

-- ─── SOCIAL TABLES (run after initial schema) ─────────────────

ALTER TABLE users
ADD COLUMN IF NOT EXISTS display_name VARCHAR(100) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS follows (
    follower_id INT NOT NULL,
    following_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (follower_id, following_id),
    FOREIGN KEY (follower_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (following_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    from_user_id INT DEFAULT NULL,
    is_read TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

USE critix;

CREATE TABLE IF NOT EXISTS discussion_comments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    discussion_id INT NOT NULL,
    user_id INT NOT NULL,
    parent_id INT DEFAULT NULL,
    body TEXT NOT NULL,
    is_deleted TINYINT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (discussion_id) REFERENCES discussions (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES discussion_comments (id) ON DELETE CASCADE,
    INDEX idx_discussion (discussion_id),
    INDEX idx_parent (parent_id),
    INDEX idx_user (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

-- ─── DISCUSSION LIKES TABLE (toggle like, prevents duplicates) ────
-- Run this migration if you already have the critix database set up.
-- The schema.sql CREATE TABLE IF NOT EXISTS above is idempotent.
CREATE TABLE IF NOT EXISTS discussion_likes (
    user_id INT NOT NULL,
    discussion_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, discussion_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (discussion_id) REFERENCES discussions (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;